### PR TITLE
Added AppBajar and Bi-Beat removed OraclePii

### PR DESCRIPTION
**Pull request by uthsobcb**
OraclePii CEO says OraclePii shut down.

### CODE REVIEW

**Comment by fazlerabbi37** [comment]
@uthsobcb, please rebase with master. 👨‍💻️

**Comment by imahbub** [comment]
@uthsobcb @fazlerabbi37 Please resolve the conflict

**Comment by uthsobcb** [comment]
i'm trying

**Comment by uthsobcb** [comment]
Close this

**Pull request closed without merging**
