### PR TITLE
Edited some symbols

### PR DESCRIPTION
**Pull request by Isr12624**
One site shutdown --- https://www.tbsnews.net/economy/hungrynaki-awaits-shutdown-652138

### CODE REVIEW

**Comment by imahbub** [comment]
> One site shutdown --- https://www.tbsnews.net/economy/hungrynaki-awaits-shutdown-652138

Remove hungrynaki from the great idea section. It's a terrible idea.

**Comment by Isr12624** [comment]
> > One site shutdown --- https://www.tbsnews.net/economy/hungrynaki-awaits-shutdown-652138
> 
> Remove hungrynaki from the great idea section. It's a terrible idea.

See my pull request commit ! I removed this and added it to the Not Active but Great Idea section.

**Comment by fazlerabbi37** [comment]
@Isr12624 there seems to be a lot of extra spaces. do remove them please.

**Comment by Isr12624** [comment]
> @Isr12624 there seems to be a lot of extra spaces. do remove them, please.

OK VI .... 😊

**Pull request merged**
